version: "3.2"

services:
    couch_db_1:
        image: couchdb:latest
        restart: always
        volumes:
            - /home/ubuntu/volume/node1/data:/opt/couchdb/data
            - /home/ubuntu/volume/node1/local.d:/opt/couchdb/etc/local.d
            - /home/ubuntu/volume/node1/vm.args:/opt/couchdb/etc/vm.args
        networks:
            default:
                aliases:
                  - couch_db_1.test.com
        deploy:
            replicas: 1
            endpoint_mode: dnsrr 

    couch_db_2:
        image: couchdb:latest
        restart: always
        volumes:
            - /home/ubuntu/volume/node2/data:/opt/couchdb/data
            - /home/ubuntu/volume/node2/local.d:/opt/couchdb/etc/local.d
            - /home/ubuntu/volume/node2/vm.args:/opt/couchdb/etc/vm.args
        networks:
            default:
                aliases:
                  - couch_db_2.test.com
        deploy:
            replicas: 1
            endpoint_mode: dnsrr 

    couch_db_3:
        image: couchdb:latest
        restart: always
        volumes:
            - /home/ubuntu/volume/node3/data:/opt/couchdb/data
            - /home/ubuntu/volume/node3/local.d:/opt/couchdb/etc/local.d
            - /home/ubuntu/volume/node3/vm.args:/opt/couchdb/etc/vm.args
        networks:
            default:
                aliases:
                  - couch_db_3.test.com
        deploy:
            replicas: 1
            endpoint_mode: dnsrr 


    couch_db_4:
        image: couchdb:latest
        restart: always
        volumes:
            - /home/ubuntu/volume/node4/data:/opt/couchdb/data
            - /home/ubuntu/volume/node4/local.d:/opt/couchdb/etc/local.d
            - /home/ubuntu/volume/node4/vm.args:/opt/couchdb/etc/vm.args
        networks:
            default:
                aliases:
                  - couch_db_4.test.com
        deploy:
            replicas: 1
            endpoint_mode: dnsrr 

    haproxy:
        image: haproxy:1.7-alpine
        ports:
          - published: 80
            target: 80
        restart: always
        volumes:
            - "/home/ubuntu/volume/haproxy:/usr/local/etc/haproxy:ro"
        deploy:
            replicas: 2


networks:
  default:
    driver: overlay